version: 2.1

orbs:
  android: circleci/android@1.0.3

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0-node
    steps:
      - checkout
      - restore_cache:
          key: android-orb-v1-
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Create Local Properties
          command: echo "sdk.dir=$ANDROID_HOME" > local.properties
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Install Android SDK & Accept Licenses
          command: |
            wget https://dl.google.com/android/repository/commandlinetools-linux-6858069_latest.zip -O sdk-tools.zip
            unzip sdk-tools.zip -d $HOME/android-sdk
            export ANDROID_SDK_ROOT=$HOME/android-sdk
            export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin
            yes | sdkmanager --licenses
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.android/build-cache
            - ~/.android/cache
      - run:
          name: Run Build
          command: ./gradlew build
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: artifact-file