name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      ANDROID_HOME: ${{ github.workspace }}/android-sdk

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Create local.properties
        run: echo "sdk.dir=${ANDROID_HOME}" > $GITHUB_WORKSPACE/local.properties

      - name: Download Dependencies
        run: ./gradlew androidDependencies

      - name: Cache Gradle Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}

      - name: Build with Gradle
        run: ./gradlew build

      - name: Add coverage report to PR
        id: kover
        uses: mi-kas/kover-report@v1
        with:
          path: |
            ${{ github.workspace }}/project1/build/reports/kover/report.xml
            ${{ github.workspace }}/project2/build/reports/kover/report.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Code Coverage
          update-comment: true
          min-coverage-overall: 80
          min-coverage-changed-files: 80
          coverage-counter-type: LINE

      - name: Vulnerability Analysis
        run: |
          npm install -g snyk
          snyk test

      - name: Run Tests
        run: ./gradlew lint test

      - name: Store Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: app/build/reports

      - name: Store APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: apk-artifact
          path: app/build/outputs/apk/debug/